---
- name: Create instance config file
  block:
    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
        skip_instances: false
  rescue:
    - name: Populate instance config when file missing
      ansible.builtin.set_fact:
        instance_conf: {}
        skip_instances: true

- name: Destroy molecule instance(s)
  amazon.aws.ec2_instance:
    profile: "{{ profile | default(omit) }}"
    state: absent
    instance_ids: "{{ item.instance_ids }}"
  register: server
  loop: "{{ instance_conf | default([]) }}"
  async: 7200
  poll: 0
  when: not skip_instances

- name: Wait for instance(s) deletion to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: ec2_jobs
  until: ec2_jobs.finished
  retries: 300
  delay: 5
  loop: "{{ (server.results | default([])) }}"
  when:
    - not skip_instances
    - server is defined
    - (server.results | default([])) | length > 0

- name: Delete remote keypair
  amazon.aws.ec2_key:
    name: "{{ item.keypair_name }}"
    profile: "{{ profile | default(omit) }}"
    state: absent
  loop: "{{ instance_conf | default([]) }}"
  when: not skip_instances

- name: Delete security group
  amazon.aws.ec2_security_group:
    group_id: "{{ item.group_id }}"
    profile: "{{ profile | default(omit) }}"
    state: absent
  register: ec2_group_jobs
  until: ec2_group_jobs.group_id is none
  retries: 300
  loop: "{{ instance_conf | default([]) }}"
  when: not skip_instances

# Mandatory configuration for Molecule to function.

- name: Populate instance config
  ansible.builtin.set_fact:
    instance_conf: {}

- name: Dump instance config
  ansible.builtin.copy:
    content: "{{ instance_conf | to_json | from_json | to_yaml }}"
    dest: "{{ molecule_instance_config }}"
    mode: "0755"
  when:
    - server is defined
    - (server.changed | default(false)) | bool
